apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-v1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"

spec:
  rules:
  - host: abc.xyza.ty
    http:
      paths:
      # Information about the Service that is created for the new application version. 
      - path: /
        backend:
          service:
            name: {{ .Values.v1.service_name }}
            port:
              number: 80
        pathType: ImplementationSpecific
